In [119]:
import numpy as np

In [120]:
#1. Create a 1D array of numbers from 0 to 9.
arr=np.array([0,1,2,3,4,5,6,7,8,9])
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [121]:
#2. Create a 3×3 numpy array of all True’s
x=np.ones(shape=(3,3),dtype=bool)
print(x)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [122]:
#3. Given an array as input, print only odd numbers as output
idx=np.where(arr%2!=0)
print(arr[idx])

[1 3 5 7 9]


In [123]:
#4. Replace all odd numbers in arr with -2
idx=np.where(arr%2!=0)
for i in idx:
    arr[i]=-2
print(arr)

[ 0 -2  2 -2  4 -2  6 -2  8 -2]


In [20]:
#5. How to reshape an array?
x=np.array([[2,33,4],[3,4,5]])
print(x,x.shape)

[[ 2 33  4]
 [ 3  4  5]] (2, 3)


In [21]:
y=x.reshape(3,2)
print(y,y.shape)

[[ 2 33]
 [ 4  3]
 [ 4  5]] (3, 2)


In [23]:
#6. Convert a 1D array to a 2D array with 2 rows
b=np.array([1,2,3,4])
print(b,b.shape,b.ndim)

[1 2 3 4] (4,) 1


In [24]:
b_=b.reshape(-1,1)
print(b_,b_.shape,b_.ndim)

[[1]
 [2]
 [3]
 [4]] (4, 1) 2


In [149]:
#7. Given an array  a  = [1,2,3,4,5,6,7,8,9] , create  new array b from a such that b includes all odd numbers and 4 multiples
a=np.array([1,2,3,4,5,6,7,8,9])
indx=np.where((a%2!=0)|(a%4==0))
b=a[indx]
print(b)


[1 3 4 5 7 8 9]


In [57]:
#8. Given array, check if there are any null values and print them out. 
lst = np.array([1, 2,np.nan, 4, 5, 6,np.nan,9])
for x in lst:
    if np.isnan(x):
        print(x)

nan
nan


In [63]:
#9. How to replace all missing values with 0 in a numpy array
lst = np.array([1, 2,np.nan, 4, 5, 6,np.nan,9])
lst[np.where(np.isnan(lst))]=0
lst.astype(int)


array([1, 2, 0, 4, 5, 6, 0, 9])

In [68]:
#10 How to find the count of each unique number in a NumPy array?
number_list = np.array([1, 1, 2, 3, 4, 4, 1])
unique,counts=np.unique(number_list,return_counts=True)
for x,y in zip(unique,counts):
    print("The number ",x," has occured ",y," times")

The number  1  has occured  3  times
The number  2  has occured  1  times
The number  3  has occured  1  times
The number  4  has occured  2  times


In [79]:
#11 How to convert a numeric to a categorical (text) array
import numpy as np
x = np.array([[2, 4, 6], [6, 8, 10]], np.int32)
print(x)
print("Data type of the array x is:",x.dtype)
y = x.astype(str)
print("New Type: ",y.dtype)
print(y)

[[ 2  4  6]
 [ 6  8 10]]
Data type of the array x is: int32
New Type:  <U11
[['2' '4' '6']
 ['6' '8' '10']]


In [93]:
#Write a program to print all numbers between 99 and 299 which are either divisible by 5 or 7.
#Exclude the elements which are divisible by both. 
np_list=np.arange(99,299)
np.array([x for x in np_list if((x%5==0 or x%7==0) and not(x%5==0 and x%7==0))])

array([100, 110, 112, 115, 119, 120, 125, 126, 130, 133, 135, 145, 147,
       150, 154, 155, 160, 161, 165, 168, 170, 180, 182, 185, 189, 190,
       195, 196, 200, 203, 205, 215, 217, 220, 224, 225, 230, 231, 235,
       238, 240, 250, 252, 255, 259, 260, 265, 266, 270, 273, 275, 285,
       287, 290, 294, 295])

In [107]:
#Write a program to reverse an array
np_ar=np.array([1,2,3,4,5])
print(np_ar[::-1])

np_ar_new=[]
for i in np_ar:
    np_ar_new.insert(0,i)
print(np_ar_new)

[5 4 3 2 1]
[5, 4, 3, 2, 1]


In [108]:
np_ar_new=[]
for i in range(1,len(np_ar)+1):
    np_ar_new.append(np_ar[-i])
print(np_ar_new)
    

[5, 4, 3, 2, 1]
